### ISSUE TITLE
Feature: "indent width" for inspect html styled

### ISSUE THREAD

**Issue by TigersWay** [cronvel/string-kit#4]
Hi,
I love your package which I use nearly everyday, especially the inspect function!
But I'd love to reduce a little it's natural indentation: 4 * "&nbsp;" is a bit too large.

Could it be possible to access `inspectStyle.html.tab` or add an `indentWidth` in the options?

Thanks

**Comment by cronvel** [comment]
@TigersWay Hi,
Thanks for the praise ;)
I added it now, as of v0.14.3. The new `tab` option overrides the style's `.tab`.
E.g.: `.inspect( { style: 'html', tab: '&nbsp;&nbsp;' } , myVar )`.

**Comment by TigersWay** [comment]
You're welcome! And working already!
_"Et un bonjour à l’Ardèche !"_

**Comment by cronvel** [comment]
@TigersWay *Tiens un ancien du coin?* ;)
*Juste par curiosité, tu utilises quoi d'autre dans cette lib? Je suis curieux parce que bien que je n'ai pas fait grand chose pour la diffuser, elle a autant de download sur npm que ma* [lib-phare](https://github.com/cronvel/terminal-kit).
*Il faudrait peut-être que je passe plus de temps sur la doc, parce qu'elle fait plein d'autres choses utiles mais non-documentées...*

**Comment by TigersWay** [comment]
@cronvel Juste un peu plus au sud: Montpellier...

Honestly, so far, I only use `inspect` in HTML mode. And I was looking for exactly when I found it, quite some months ago.

**Comment by cronvel** [comment]
@TigersWay Ok thanks for the feedback! ;)
